
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class mySym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int AND = 19;
  public static final int ELSE = 6;
  public static final int UPCARROT = 21;
  public static final int PLUS = 13;
  public static final int OR = 20;
  public static final int EQUAL = 28;
  public static final int THEN = 7;
  public static final int NOTEQUAL = 29;
  public static final int IN = 23;
  public static final int SEMI = 10;
  public static final int WHILE = 8;
  public static final int END = 3;
  public static final int IDENTIFIER = 4;
  public static final int GREATER = 31;
  public static final int IF = 5;
  public static final int LESSEQUAL = 27;
  public static final int COLON = 11;
  public static final int BEGIN = 2;
  public static final int DO = 9;
  public static final int LESSTHAN = 26;
  public static final int EOF = 0;
  public static final int DIVIDE = 18;
  public static final int EXC = 16;
  public static final int MINUS = 14;
  public static final int CONST = 24;
  public static final int error = 1;
  public static final int LET = 22;
  public static final int ASSIGN = 12;
  public static final int DASH = 15;
  public static final int INTEGER = 32;
  public static final int GREATEREQUAL = 30;
  public static final int VAR = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "IDENTIFIER",
  "IF",
  "ELSE",
  "THEN",
  "WHILE",
  "DO",
  "SEMI",
  "COLON",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "DASH",
  "EXC",
  "TIMES",
  "DIVIDE",
  "AND",
  "OR",
  "UPCARROT",
  "LET",
  "IN",
  "CONST",
  "VAR",
  "LESSTHAN",
  "LESSEQUAL",
  "EQUAL",
  "NOTEQUAL",
  "GREATEREQUAL",
  "GREATER",
  "INTEGER"
  };
}

