
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class mySym {
  /* terminals */
  public static final int INTEGER = 9;
  public static final int SEMI = 5;
  public static final int EOF = 0;
  public static final int PLUS = 7;
  public static final int ASSIGN = 6;
  public static final int error = 1;
  public static final int TIMES = 8;
  public static final int IDENTIFIER = 4;
  public static final int END = 3;
  public static final int BEGIN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "IDENTIFIER",
  "SEMI",
  "ASSIGN",
  "PLUS",
  "TIMES",
  "INTEGER"
  };
}

